- onabort
- onauxclick
- oncancel
- oncanplay
- oncanplaythrough
- onchange
- onclick
- onclose
- oncontextmenu
- oncuechange
- ondblclick
- ondrag
- ondragend
- ondragenter
- ondragexit
- ondragleave
- ondragover
- ondragstart
- ondrop
- ondurationchange
- onemptied
- onended
- oninput
- oninvalid
- onkeydown
- onkeypress
- onkeyup
- onloadeddata
- onloadedmetadata
- onloadend
- onloadstart
- onmousedown
- onmouseenter
- onmouseleave
- onmousemove
- onmouseout
- onmouseover
- onmouseup
- onwheel
- onpause
- onplay
- onplaying
- onprogress
- onratechange
- onreset
- onsecuritypolicyviolation
- onseeked
- onseeking
- onselect
- onstalled
- onsubmit
- onsuspend
- ontimeupdate
- ontoggle
- onvolumechange
- onwaiting